name: Generate Python Docs

on:
  push:
    branches:
      - main

jobs:
  auto_generate_docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        pip install .
    
    - name: Switch to Dev Branch
      run: git checkout -b pages || git checkout pages
    
    - name: Check if docs folder exists
      run: |
        if [ -d "docs" ]; then
          rm -rf docs
        fi

    - name: Generate Docs
      run: |
        pdoc GenomeSigInfer -o docs
    
    - name: Commit and Push Docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "alfonsobusker@gmail.com"
        git config --local user.name "AlfonsoJan"
        git pull origin pages  # Pull changes from remote pages branch
        git add docs
        git commit -m "Auto generated Python docs"
        git push origin HEAD:pages  # Push to pages branch
